<section id="cards">
	<div class="row">
		<div class="small-12 medium-6 columns">
			<a href="https://github.com/sudouc" class="callout github">
					<h4>Sudo on GitHub</h4>
					<p>Browse the repositories and maybe share your own project with everyone.</p>
			</a>
		</div>
		<div class="small-12 medium-6 columns">
			<a href="/about/" class="callout ninja">
				<h4>Become a Ninja Developer</h4>
				<p>Gain knowledge, learn industry standard skills, make things happen.</p>
			</a>
		</div>
	</div>
</section>
