<section id="cards">
	<div class="grid-container">
        <div class="grid-x grid-padding-x align-stretch">
            <div class="small-12 medium-6 cell">
                <a href="https://github.com/sudouc" class="callout github">
                        <h4>Sudo on GitHub</h4>
                        <p>Browse the Git Repo or Share your own project with everyone.</p>
                </a>
            </div>
            <div class="small-12 medium-6 cell">
                <a href="/about/" class="callout ninja">
                    <h4>Become a Ninja Developer</h4>
                    <p>Gain knowledge, learn industry standard skills and become a real developer.</p>
                </a>
            </div>
        </div>
	</div>
</section>
