<footer class="<!--#echo var="footerType" -->">
    <div class="grid-container">
        <div class="grid-x grid-padding-x">
            <div class="auto cell">
                <div class="legal"><a href="mailto:pr@sudo.org.au"><i class="fa fa-envelope"></i> &nbsp; &nbsp; &nbsp;Contact Us</a></div>
                <div class="legal">Copyright &copy; 2017 Sudo. All Rights Reserved.</div>
            </div>
            <div class="auto cell text-right">
                <div class="unican"></div>
            </div>
        </div>
    </div>
</footer>
