<meta name="Description" content="The Australian Armed Forces, often referred to as just 'AAF', is a co-op based ARMA 3 squad formed in late 2008; however its roots extend back to ARMA 2, ARMA and as far back as 2001 with Operation Flashpoint." />

<meta property="og:title" content="Australian Armed Forces – Arma 3 Unit" />
<meta property="og:description" content="The Australian Armed Forces, often referred to as just 'AAF', is a co-op based ARMA 3 squad formed in late 2008; however its roots extend back to ARMA 2, ARMA and as far back as 2001 with Operation Flashpoint." />
<meta name="Keywords" content="Australian Armed Forces Arma 3 Gaming Community Unit Teamwork Leadership Communication ">
<meta property="og:url" content="http://australianarmedforces.org/mods/" />
<meta property="og:locale" content="en_AU" />
<meta property="og:image" content="http://australianarmedforces.org/aaf-global/images/og_image.png" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Australian Armed Forces – Arma 3 Unit" />
<meta name="theme-color" content="#2583d9">

<link rel="home" href="http://australianarmedforces.org/" />
<link rel="index" href="http://australianarmedforces.org/" />
