



<meta name="Keywords" content="">

<meta property="og:locale" content="en_AU" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Sudo – UC's Developers Organisation" />
<meta name="theme-color" content="#778eff">

<link rel="home" href="https://sudo.org.au/" />
<link rel="index" href="https://sudo.org.au/" />


<!--#set var="registerURL" value="http://platform.sudo.org.au/login/create" -->
<!--#set var="signInURL" value="http://platform.sudo.org.au/login" -->
<!--#set var="footerType" value="" -->
