<meta name="Description" content="Sudo is the University of Canberra's Developer's Society." />

<meta property="og:title" content="Sudo – UC's Developers Organisation" />
<meta property="og:description" content="Sudo is the University of Canberra's Developer's Society." />
<meta name="Keywords" content="">
<meta property="og:url" content="https://sudo.org.au/" />
<meta property="og:locale" content="en_AU" />
<meta property="og:image" content="https://sudo.org.au/sudo-global/images/og_image.png" />
<meta property="og:type" content="website" />
<meta property="og:site_name" content="Sudo – UC's Developers Organisation" />
<meta name="theme-color" content="#778eff">

<link rel="home" href="https://sudo.org.au/" />
<link rel="index" href="https://sudo.org.au/" />
