<header class="overlap"  data-sticky-container>
	<div class="row">
		<div class="column">
			<a href="/">
				<div class="logo"></div>
			</a>
		</div>
		<div class="column text-center show-for-medium">
			<nav>
				<ul class="menu">
			   <li>
				 <a href="/about/">About</a>
			   </li>
			   <li>
				 <a href="/projects/">Projects</a>
			   </li>
			   <li>
				 <a href="#">Get in Touch</a>
			   </li>
			 </ul>
			</nav>
		</div>
		<div class="column text-right">
			<div class="mobile-menu hide-for-medium"></div>
			<a href="" class="signin show-for-medium">Sign In</a>
		</div>
	</div>
</header>
